services:
  lizbernal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lizbernal
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=prosuite"
      - "traefik.http.routers.lizbernal-apex.rule=Host(`lizbernal.mx`)"
      - "traefik.http.routers.lizbernal-apex.entrypoints=websecure"
      - "traefik.http.routers.lizbernal-apex.tls.certresolver=letsencrypt-dns"
      - "traefik.http.routers.lizbernal-apex.service=lizbernal"
      - "traefik.http.routers.lizbernal-www.rule=Host(`www.lizbernal.mx`)"
      - "traefik.http.routers.lizbernal-www.entrypoints=websecure"
      - "traefik.http.routers.lizbernal-www.tls.certresolver=letsencrypt-dns"
      - "traefik.http.routers.lizbernal-www.service=lizbernal"
      - "traefik.http.services.lizbernal.loadbalancer.server.port=3000"
    networks:
      - prosuite

networks:
  prosuite:
    external: true
